#!/usr/bin/env bash
set -Eeuo pipefail

REPOSITORY="HDR-Performance/Neptune-3-Maxout-Configs"
BRANCH="${HDR_BRANCH:-main}"
RAW_BASE="${HDR_RAW_BASE:-https://raw.githubusercontent.com/${REPOSITORY}/${BRANCH}}"
CONFIG_DIR="${HDR_CONFIG_DIR:-${HOME}/printer_data/config}"
KS_DIR="${HDR_KLIPPERSCREEN_DIR:-${HOME}/KlipperScreen}"
KS_CONFIG="${CONFIG_DIR}/KlipperScreen.conf"
PANEL_TARGET="${KS_DIR}/panels/bed_screw_location.py"
TRANSFORM_TARGET="${KS_DIR}/panels/hdr_bed_screw_transform.py"
Z_SETUP_TARGET="${KS_DIR}/panels/z_offset_setup.py"
STAMP="$(date +%Y%m%d-%H%M%S)"
TEMP_DIR="$(mktemp -d -t hdr-bed-screw-ui.XXXXXX)"
trap 'rm -rf -- "${TEMP_DIR}"' EXIT

die() { printf 'ERROR: %s\n' "$*" >&2; exit 1; }
download() {
  if command -v curl >/dev/null 2>&1; then
    curl --fail --location --silent --show-error "$1" --output "$2"
  elif command -v wget >/dev/null 2>&1; then
    wget -q -O "$2" "$1"
  else
    die "curl or wget is required."
  fi
}

[[ -d "${CONFIG_DIR}" && -f "${CONFIG_DIR}/printer.cfg" ]] || die "Klipper config was not found at ${CONFIG_DIR}."
[[ -d "${KS_DIR}/panels" ]] || die "KlipperScreen panels directory was not found at ${KS_DIR}/panels."
mkdir -p "${CONFIG_DIR}/custom/generated" "${CONFIG_DIR}/custom/state"
touch "${KS_CONFIG}"

# Make the generated coordinates authoritative without replacing any other
# printer.cfg content. Existing model-specific screw coordinates are migrated
# only when the generated file does not already contain an active section.
cp -a "${CONFIG_DIR}/printer.cfg" "${CONFIG_DIR}/printer.cfg.hdr-bed-screw-backup-${STAMP}"
python3 - "${CONFIG_DIR}/printer.cfg" "${CONFIG_DIR}/custom/generated/screws_tilt_adjust.cfg" <<'PY'
from pathlib import Path
import sys

printer = Path(sys.argv[1])
generated = Path(sys.argv[2])
text = printer.read_text(encoding="utf-8")
lines = text.splitlines(keepends=True)
start = next((i for i, line in enumerate(lines) if line.strip() == "[screws_tilt_adjust]"), None)
section = None
if start is not None:
    end = next((i for i in range(start + 1, len(lines)) if lines[i].lstrip().startswith("[")), len(lines))
    section = "".join(lines[start:end]).strip() + "\n"
    text = "".join(lines[:start] + lines[end:])

active_generated = generated.exists() and "[screws_tilt_adjust]" in generated.read_text(encoding="utf-8")
if section and not active_generated:
    generated.write_text(
        "# Migrated by HDR Performance Bed Screw Location.\n" + section,
        encoding="utf-8",
        newline="\n",
    )

anchor = "[include KAMP_Settings.cfg]"
includes = [
    "[include custom/generated/screws_tilt_adjust.cfg]",
    "[include custom/macros/bed_screw_location.cfg]",
    "[include custom/macros/manual_bed_tramming.cfg]",
]
for include in includes:
    if include not in text:
        if anchor in text:
            text = text.replace(anchor, anchor + "\n" + include, 1)
        else:
            text = include + "\n" + text
        anchor = include
while "\n\n\n" in text:
    text = text.replace("\n\n\n", "\n\n")
printer.write_text(text, encoding="utf-8", newline="\n")
PY

download "${RAW_BASE}/tools/klipperscreen-panels/bed_screw_location.py" "${TEMP_DIR}/panel.py"
download "${RAW_BASE}/tools/klipperscreen-panels/hdr_bed_screw_transform.py" "${TEMP_DIR}/transform.py"
download "${RAW_BASE}/tools/klipperscreen-panels/z_offset_setup.py" "${TEMP_DIR}/z-offset-setup.py"
sed "s|__HDR_CONFIG_DIR__|${CONFIG_DIR//|/\\|}|g" "${TEMP_DIR}/panel.py" >"${TEMP_DIR}/panel-rendered.py"
if grep -q '__HDR_CONFIG_DIR__' "${TEMP_DIR}/panel-rendered.py"; then
  die "The Bed Screw Location panel still contains an unresolved config-path placeholder."
fi
python3 -m py_compile "${TEMP_DIR}/panel-rendered.py" || die "The Bed Screw Location panel failed Python validation."
python3 -m py_compile "${TEMP_DIR}/transform.py" || die "The Bed Screw Location orientation helper failed Python validation."
python3 -m py_compile "${TEMP_DIR}/z-offset-setup.py" || die "The Z Offset Setup panel failed Python validation."

if [[ -f "${PANEL_TARGET}" ]]; then
  cp -a "${PANEL_TARGET}" "${PANEL_TARGET}.hdr-backup-${STAMP}"
fi
install -m 0644 "${TEMP_DIR}/panel-rendered.py" "${PANEL_TARGET}"
if [[ -f "${TRANSFORM_TARGET}" ]]; then
  cp -a "${TRANSFORM_TARGET}" "${TRANSFORM_TARGET}.hdr-backup-${STAMP}"
fi
install -m 0644 "${TEMP_DIR}/transform.py" "${TRANSFORM_TARGET}"
for pair in "${TEMP_DIR}/z-offset-setup.py:${Z_SETUP_TARGET}"; do
  source="${pair%%:*}"
  target="${pair#*:}"
  if [[ -f "${target}" ]]; then
    cp -a "${target}" "${target}.hdr-backup-${STAMP}"
  fi
  install -m 0644 "${source}" "${target}"
done

if [[ ! -f "${CONFIG_DIR}/custom/generated/screws_tilt_adjust.cfg" ]]; then
  cat >"${CONFIG_DIR}/custom/generated/screws_tilt_adjust.cfg" <<'EOF'
# Generated by HDR Performance Bed Screw Location after all positions are saved.
# This intentionally contains no Klipper section until setup is completed.
EOF
fi

clean="${TEMP_DIR}/KlipperScreen.clean"
awk '
  /^# HDR Performance bed screw location begin$/ {skip=1; next}
  /^# HDR Performance bed screw location end$/ {skip=0; next}
  !skip {print}
' "${KS_CONFIG}" >"${clean}"
block="${TEMP_DIR}/menu.block"
cat >"${block}" <<'EOF'

# HDR Performance bed screw location begin
[menu __main more hdr_bed_screw_location]
name: Bed Screw Location
icon: bed-level
panel: bed_screw_location
enable: {{ printer.idle_timeout.state != "Printing" }}
# HDR Performance bed screw location end
EOF

if grep -q '^#~# --- Do not edit below this line' "${clean}"; then
  awk -v block="${block}" '
    !inserted && /^#~# --- Do not edit below this line/ {
      while ((getline line < block) > 0) print line
      close(block); inserted=1
    }
    {print}
  ' "${clean}" >"${TEMP_DIR}/KlipperScreen.new"
else
  cat "${clean}" "${block}" >"${TEMP_DIR}/KlipperScreen.new"
fi
install -m 0644 "${TEMP_DIR}/KlipperScreen.new" "${KS_CONFIG}"

if command -v systemctl >/dev/null 2>&1 && systemctl cat KlipperScreen.service >/dev/null 2>&1; then
  sudo systemctl restart KlipperScreen
else
  printf 'KlipperScreen was not restarted automatically. Restart it to load the new panel.\n'
fi
printf 'Installed Bed Screw Location panel: %s\n' "${PANEL_TARGET}"
printf 'Persistent locations: %s\n' "${CONFIG_DIR}/custom/state/bed_screw_locations.json"

